### ISSUE TITLE
Organization secrets

### ISSUE THREAD

**Issue by rodrigondec** [hmanzur/actions-set-secret#5]
Thank you for your PR #3 

But there are some missing things on your PR that I managed to do on #4 (which you closed).

# Organization secret
I want to upload a secret to my organization, not to my repo (which is from my organization).

Your variable `_base` is correct. But you are still passing a `/:repo/` hardcoded on your URL.

https://github.com/hmanzur/actions-set-secret/blob/f2a75ae083cdd3aa8a400eca344ec232b5c8f7a1/src/api.js#L29

When uploading to organization level secret, it must be passed the `owner`/`organization_name` in the url
```js
let { data } = await this.octokit.request('GET /:base/:owner/actions/secrets/public-key', { 
```

## Input owner
Shouldn't be better to create a input `owner` for this on the action?

# Input repository
Your input is using a `{github.repository}`.

This context returns `owner/repository`? I think it will return `repository` only.

https://github.com/hmanzur/actions-set-secret/blob/f2a75ae083cdd3aa8a400eca344ec232b5c8f7a1/action.yml#L22

The urls for repo are:
- `PUT /repos/:owner/:repo/actions/secrets/:secret_name`
- `GET /repos/:owner/:repo/actions/secrets/public-key`

You are obfuscating the owner attribute! This caused me a lot a confusion. And a made those changes on PR #4 to declare it explicitly.

# References for repository
- https://developer.github.com/v3/actions/secrets/#get-a-repository-public-key
- https://developer.github.com/v3/actions/secrets/#create-or-update-a-repository-secret

# References for organization
- https://developer.github.com/v3/actions/secrets/#get-an-organization-public-key
- https://developer.github.com/v3/actions/secrets/#create-or-update-an-organization-secret

**Comment by rodrigondec** [comment]
I see, then if I pass 

```
with:
  - repository: my_org
```
without the `/repo` it works. 

In my opinion it would be better to declare owner and repository separately. But it would indeed add some complexity to the code.

It's your call and I trust you, to me this works.

I just ask you to update the readme accordingly the explain this quirky behavior :wink: 

I did some changes to the readme on PR #4. If you would like I can improve your readme with this behavior.

**Comment by hmanzur** [comment]
I added more examples in the [README.md](https://github.com/hmanzur/actions-set-secret/blob/master/README.md)

**Comment by rodrigondec** [comment]
@hmanzur to send the data to a organization secret, there must be the the `visibility` attribute on the `data` payload.

https://github.com/hmanzur/actions-set-secret/blob/a8b1c756ab377723e9f5ad0419f7b0fae9c5df04/src/api.js#L67

https://developer.github.com/v3/actions/secrets/#create-or-update-an-organization-secret

![image](https://user-images.githubusercontent.com/3301060/89835645-80485980-db3b-11ea-8dc3-f8ace0402513.png)
