### ISSUE TITLE
Visibility not passed

### ISSUE THREAD

**Issue by rodrigondec** [hmanzur/actions-set-secret#7]
# Resume
I'm setting the `visibility` input. But the input is not passed to github API!

# Where is your method `isOrg`?
This method called is not present in your `src/api.js`
https://github.com/hmanzur/actions-set-secret/blob/c9c16be2aa4f0c938fa4601f62f259b32aa5d954/index.js#L16

# Proofs
![image](https://user-images.githubusercontent.com/3301060/90155222-73a54a80-dd61-11ea-8bb0-d4120f90c79e.png)
![image](https://user-images.githubusercontent.com/3301060/90155282-86b81a80-dd61-11ea-93b8-64c9c4f1e0d3.png)
![image](https://user-images.githubusercontent.com/3301060/90155360-99325400-dd61-11ea-9a1f-453c3ac01ff1.png)

**Comment by hmanzur** [comment]
Now is fixed. You can check again
